// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: internal/dinosaur/pkg/api/private/grpc/fleet-manger-private.proto

package fleetmanager_private_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CentralVersions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Central         string `protobuf:"bytes,1,opt,name=central,proto3" json:"central,omitempty"`
	CentralOperator string `protobuf:"bytes,2,opt,name=centralOperator,proto3" json:"centralOperator,omitempty"`
}

func (x *CentralVersions) Reset() {
	*x = CentralVersions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CentralVersions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CentralVersions) ProtoMessage() {}

func (x *CentralVersions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CentralVersions.ProtoReflect.Descriptor instead.
func (*CentralVersions) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{0}
}

func (x *CentralVersions) GetCentral() string {
	if x != nil {
		return x.Central
	}
	return ""
}

func (x *CentralVersions) GetCentralOperator() string {
	if x != nil {
		return x.CentralOperator
	}
	return ""
}

type Condition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type               string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Reason             string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status             string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LastTransitionTime string `protobuf:"bytes,5,opt,name=lastTransitionTime,proto3" json:"lastTransitionTime,omitempty"`
}

func (x *Condition) Reset() {
	*x = Condition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{1}
}

func (x *Condition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Condition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Condition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Condition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Condition) GetLastTransitionTime() string {
	if x != nil {
		return x.LastTransitionTime
	}
	return ""
}

type CentralStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conditions []*Condition     `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Versions   *CentralVersions `protobuf:"bytes,2,opt,name=versions,proto3" json:"versions,omitempty"`
}

func (x *CentralStatus) Reset() {
	*x = CentralStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CentralStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CentralStatus) ProtoMessage() {}

func (x *CentralStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CentralStatus.ProtoReflect.Descriptor instead.
func (*CentralStatus) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{2}
}

func (x *CentralStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *CentralStatus) GetVersions() *CentralVersions {
	if x != nil {
		return x.Versions
	}
	return nil
}

type UpdateCentralStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentCluster string                    `protobuf:"bytes,1,opt,name=agent_cluster,json=agentCluster,proto3" json:"agent_cluster,omitempty"`
	Updates      map[string]*CentralStatus `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UpdateCentralStatusRequest) Reset() {
	*x = UpdateCentralStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCentralStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCentralStatusRequest) ProtoMessage() {}

func (x *UpdateCentralStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCentralStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCentralStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCentralStatusRequest) GetAgentCluster() string {
	if x != nil {
		return x.AgentCluster
	}
	return ""
}

func (x *UpdateCentralStatusRequest) GetUpdates() map[string]*CentralStatus {
	if x != nil {
		return x.Updates
	}
	return nil
}

type UpdateCentralStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateCentralStatusResponse) Reset() {
	*x = UpdateCentralStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCentralStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCentralStatusResponse) ProtoMessage() {}

func (x *UpdateCentralStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCentralStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateCentralStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCentralStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ManagedCentralMetadataAnnotations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasId          string `protobuf:"bytes,1,opt,name=mas_id,json=masId,proto3" json:"mas_id,omitempty"`
	MasPlacementId string `protobuf:"bytes,2,opt,name=mas_placement_id,json=masPlacementId,proto3" json:"mas_placement_id,omitempty"`
}

func (x *ManagedCentralMetadataAnnotations) Reset() {
	*x = ManagedCentralMetadataAnnotations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentralMetadataAnnotations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentralMetadataAnnotations) ProtoMessage() {}

func (x *ManagedCentralMetadataAnnotations) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentralMetadataAnnotations.ProtoReflect.Descriptor instead.
func (*ManagedCentralMetadataAnnotations) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{5}
}

func (x *ManagedCentralMetadataAnnotations) GetMasId() string {
	if x != nil {
		return x.MasId
	}
	return ""
}

func (x *ManagedCentralMetadataAnnotations) GetMasPlacementId() string {
	if x != nil {
		return x.MasPlacementId
	}
	return ""
}

type ManagedCentralMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name              string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace         string                             `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Annotations       *ManagedCentralMetadataAnnotations `protobuf:"bytes,3,opt,name=annotations,proto3" json:"annotations,omitempty"`
	DeletionTimestamp string                             `protobuf:"bytes,4,opt,name=deletion_timestamp,json=deletionTimestamp,proto3" json:"deletion_timestamp,omitempty"`
}

func (x *ManagedCentralMetadata) Reset() {
	*x = ManagedCentralMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentralMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentralMetadata) ProtoMessage() {}

func (x *ManagedCentralMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentralMetadata.ProtoReflect.Descriptor instead.
func (*ManagedCentralMetadata) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{6}
}

func (x *ManagedCentralMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManagedCentralMetadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ManagedCentralMetadata) GetAnnotations() *ManagedCentralMetadataAnnotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ManagedCentralMetadata) GetDeletionTimestamp() string {
	if x != nil {
		return x.DeletionTimestamp
	}
	return ""
}

type ManagedCentralSpecAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientSecret string `protobuf:"bytes,1,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	ClientId     string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OwnerUserId  string `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	OwnerOrgId   string `protobuf:"bytes,4,opt,name=owner_org_id,json=ownerOrgId,proto3" json:"owner_org_id,omitempty"`
	Issuer       string `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
}

func (x *ManagedCentralSpecAuth) Reset() {
	*x = ManagedCentralSpecAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentralSpecAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentralSpecAuth) ProtoMessage() {}

func (x *ManagedCentralSpecAuth) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentralSpecAuth.ProtoReflect.Descriptor instead.
func (*ManagedCentralSpecAuth) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{7}
}

func (x *ManagedCentralSpecAuth) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *ManagedCentralSpecAuth) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ManagedCentralSpecAuth) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *ManagedCentralSpecAuth) GetOwnerOrgId() string {
	if x != nil {
		return x.OwnerOrgId
	}
	return ""
}

func (x *ManagedCentralSpecAuth) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

type ManagedCentralSpecUiEndpointTLS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert string `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ManagedCentralSpecUiEndpointTLS) Reset() {
	*x = ManagedCentralSpecUiEndpointTLS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentralSpecUiEndpointTLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentralSpecUiEndpointTLS) ProtoMessage() {}

func (x *ManagedCentralSpecUiEndpointTLS) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentralSpecUiEndpointTLS.ProtoReflect.Descriptor instead.
func (*ManagedCentralSpecUiEndpointTLS) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{8}
}

func (x *ManagedCentralSpecUiEndpointTLS) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *ManagedCentralSpecUiEndpointTLS) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ManagedCentralSpecUiEndpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string                           `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Tls  *ManagedCentralSpecUiEndpointTLS `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
}

func (x *ManagedCentralSpecUiEndpoint) Reset() {
	*x = ManagedCentralSpecUiEndpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentralSpecUiEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentralSpecUiEndpoint) ProtoMessage() {}

func (x *ManagedCentralSpecUiEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentralSpecUiEndpoint.ProtoReflect.Descriptor instead.
func (*ManagedCentralSpecUiEndpoint) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{9}
}

func (x *ManagedCentralSpecUiEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ManagedCentralSpecUiEndpoint) GetTls() *ManagedCentralSpecUiEndpointTLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

type ManagedCentralSpecDataEndpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *ManagedCentralSpecDataEndpoint) Reset() {
	*x = ManagedCentralSpecDataEndpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentralSpecDataEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentralSpecDataEndpoint) ProtoMessage() {}

func (x *ManagedCentralSpecDataEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentralSpecDataEndpoint.ProtoReflect.Descriptor instead.
func (*ManagedCentralSpecDataEndpoint) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{10}
}

func (x *ManagedCentralSpecDataEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type ResourceList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu    string `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory string `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
}

func (x *ResourceList) Reset() {
	*x = ResourceList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceList) ProtoMessage() {}

func (x *ResourceList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceList.ProtoReflect.Descriptor instead.
func (*ResourceList) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceList) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceList) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

type ResourceRequirements struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests *ResourceList `protobuf:"bytes,1,opt,name=requests,proto3" json:"requests,omitempty"`
	Limits   *ResourceList `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
}

func (x *ResourceRequirements) Reset() {
	*x = ResourceRequirements{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirements) ProtoMessage() {}

func (x *ResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirements.ProtoReflect.Descriptor instead.
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{12}
}

func (x *ResourceRequirements) GetRequests() *ResourceList {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ResourceRequirements) GetLimits() *ResourceList {
	if x != nil {
		return x.Limits
	}
	return nil
}

type ManagedCentralSpecCentral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources *ResourceRequirements `protobuf:"bytes,1,opt,name=resources,proto3" json:"resources,omitempty"`
}

func (x *ManagedCentralSpecCentral) Reset() {
	*x = ManagedCentralSpecCentral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentralSpecCentral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentralSpecCentral) ProtoMessage() {}

func (x *ManagedCentralSpecCentral) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentralSpecCentral.ProtoReflect.Descriptor instead.
func (*ManagedCentralSpecCentral) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{13}
}

func (x *ManagedCentralSpecCentral) GetResources() *ResourceRequirements {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ManagedCentralSpecScannerAnalyzerScaling struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AutoScaling string `protobuf:"bytes,1,opt,name=auto_scaling,json=autoScaling,proto3" json:"auto_scaling,omitempty"`
	Replicas    int32  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	MinReplicas int32  `protobuf:"varint,3,opt,name=minReplicas,proto3" json:"minReplicas,omitempty"`
	MaxReplicas int32  `protobuf:"varint,4,opt,name=maxReplicas,proto3" json:"maxReplicas,omitempty"`
}

func (x *ManagedCentralSpecScannerAnalyzerScaling) Reset() {
	*x = ManagedCentralSpecScannerAnalyzerScaling{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentralSpecScannerAnalyzerScaling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentralSpecScannerAnalyzerScaling) ProtoMessage() {}

func (x *ManagedCentralSpecScannerAnalyzerScaling) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentralSpecScannerAnalyzerScaling.ProtoReflect.Descriptor instead.
func (*ManagedCentralSpecScannerAnalyzerScaling) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{14}
}

func (x *ManagedCentralSpecScannerAnalyzerScaling) GetAutoScaling() string {
	if x != nil {
		return x.AutoScaling
	}
	return ""
}

func (x *ManagedCentralSpecScannerAnalyzerScaling) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *ManagedCentralSpecScannerAnalyzerScaling) GetMinReplicas() int32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *ManagedCentralSpecScannerAnalyzerScaling) GetMaxReplicas() int32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

type ManagedCentralSpecScannerAnalyzer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resources *ResourceRequirements `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
}

func (x *ManagedCentralSpecScannerAnalyzer) Reset() {
	*x = ManagedCentralSpecScannerAnalyzer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentralSpecScannerAnalyzer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentralSpecScannerAnalyzer) ProtoMessage() {}

func (x *ManagedCentralSpecScannerAnalyzer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentralSpecScannerAnalyzer.ProtoReflect.Descriptor instead.
func (*ManagedCentralSpecScannerAnalyzer) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{15}
}

func (x *ManagedCentralSpecScannerAnalyzer) GetResources() *ResourceRequirements {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ManagedCentralSpecScannerDb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *ManagedCentralSpecScannerDb) Reset() {
	*x = ManagedCentralSpecScannerDb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentralSpecScannerDb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentralSpecScannerDb) ProtoMessage() {}

func (x *ManagedCentralSpecScannerDb) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentralSpecScannerDb.ProtoReflect.Descriptor instead.
func (*ManagedCentralSpecScannerDb) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{16}
}

func (x *ManagedCentralSpecScannerDb) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type ManagedCentralSpecScanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Analyzer *ManagedCentralSpecScannerAnalyzer `protobuf:"bytes,1,opt,name=analyzer,proto3" json:"analyzer,omitempty"`
	Db       *ManagedCentralSpecScannerDb       `protobuf:"bytes,2,opt,name=db,proto3" json:"db,omitempty"`
}

func (x *ManagedCentralSpecScanner) Reset() {
	*x = ManagedCentralSpecScanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentralSpecScanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentralSpecScanner) ProtoMessage() {}

func (x *ManagedCentralSpecScanner) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentralSpecScanner.ProtoReflect.Descriptor instead.
func (*ManagedCentralSpecScanner) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{17}
}

func (x *ManagedCentralSpecScanner) GetAnalyzer() *ManagedCentralSpecScannerAnalyzer {
	if x != nil {
		return x.Analyzer
	}
	return nil
}

func (x *ManagedCentralSpecScanner) GetDb() *ManagedCentralSpecScannerDb {
	if x != nil {
		return x.Db
	}
	return nil
}

type ManagedCentralSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owners       []string                        `protobuf:"bytes,1,rep,name=owners,proto3" json:"owners,omitempty"`
	Auth         *ManagedCentralSpecAuth         `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	UiEndpoint   *ManagedCentralSpecUiEndpoint   `protobuf:"bytes,3,opt,name=ui_endpoint,json=uiEndpoint,proto3" json:"ui_endpoint,omitempty"`
	DataEndpoint *ManagedCentralSpecDataEndpoint `protobuf:"bytes,4,opt,name=data_endpoint,json=dataEndpoint,proto3" json:"data_endpoint,omitempty"`
	Versions     *CentralVersions                `protobuf:"bytes,5,opt,name=versions,proto3" json:"versions,omitempty"`
	Central      *ManagedCentralSpecCentral      `protobuf:"bytes,6,opt,name=central,proto3" json:"central,omitempty"`
	Scanner      *ManagedCentralSpecScanner      `protobuf:"bytes,7,opt,name=scanner,proto3" json:"scanner,omitempty"`
}

func (x *ManagedCentralSpec) Reset() {
	*x = ManagedCentralSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentralSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentralSpec) ProtoMessage() {}

func (x *ManagedCentralSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentralSpec.ProtoReflect.Descriptor instead.
func (*ManagedCentralSpec) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{18}
}

func (x *ManagedCentralSpec) GetOwners() []string {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *ManagedCentralSpec) GetAuth() *ManagedCentralSpecAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ManagedCentralSpec) GetUiEndpoint() *ManagedCentralSpecUiEndpoint {
	if x != nil {
		return x.UiEndpoint
	}
	return nil
}

func (x *ManagedCentralSpec) GetDataEndpoint() *ManagedCentralSpecDataEndpoint {
	if x != nil {
		return x.DataEndpoint
	}
	return nil
}

func (x *ManagedCentralSpec) GetVersions() *CentralVersions {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ManagedCentralSpec) GetCentral() *ManagedCentralSpecCentral {
	if x != nil {
		return x.Central
	}
	return nil
}

func (x *ManagedCentralSpec) GetScanner() *ManagedCentralSpecScanner {
	if x != nil {
		return x.Scanner
	}
	return nil
}

type ManagedCentral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                  `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *ManagedCentralMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *ManagedCentralSpec     `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	RequestStatus string                  `protobuf:"bytes,5,opt,name=request_status,json=requestStatus,proto3" json:"request_status,omitempty"`
}

func (x *ManagedCentral) Reset() {
	*x = ManagedCentral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedCentral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedCentral) ProtoMessage() {}

func (x *ManagedCentral) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedCentral.ProtoReflect.Descriptor instead.
func (*ManagedCentral) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{19}
}

func (x *ManagedCentral) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ManagedCentral) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ManagedCentral) GetMetadata() *ManagedCentralMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ManagedCentral) GetSpec() *ManagedCentralSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ManagedCentral) GetRequestStatus() string {
	if x != nil {
		return x.RequestStatus
	}
	return ""
}

type GetCentralsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentCluster string `protobuf:"bytes,1,opt,name=agent_cluster,json=agentCluster,proto3" json:"agent_cluster,omitempty"`
}

func (x *GetCentralsRequest) Reset() {
	*x = GetCentralsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCentralsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCentralsRequest) ProtoMessage() {}

func (x *GetCentralsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCentralsRequest.ProtoReflect.Descriptor instead.
func (*GetCentralsRequest) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{20}
}

func (x *GetCentralsRequest) GetAgentCluster() string {
	if x != nil {
		return x.AgentCluster
	}
	return ""
}

type GetCentralsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Centrals []*ManagedCentral `protobuf:"bytes,1,rep,name=centrals,proto3" json:"centrals,omitempty"`
}

func (x *GetCentralsResponse) Reset() {
	*x = GetCentralsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCentralsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCentralsResponse) ProtoMessage() {}

func (x *GetCentralsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCentralsResponse.ProtoReflect.Descriptor instead.
func (*GetCentralsResponse) Descriptor() ([]byte, []int) {
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP(), []int{21}
}

func (x *GetCentralsResponse) GetCentrals() []*ManagedCentral {
	if x != nil {
		return x.Centrals
	}
	return nil
}

var File_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto protoreflect.FileDescriptor

var file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDesc = []byte{
	0x0a, 0x41, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x69, 0x6e, 0x6f, 0x73,
	0x61, 0x75, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2d, 0x6d,
	0x61, 0x6e, 0x67, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x22, 0x55, 0x0a, 0x0f, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x12, 0x28,
	0x0a, 0x0f, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x99, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x0d, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x37, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x39, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x08, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xeb, 0x01, 0x0a, 0x1a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x4f,
	0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x35, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x1a,
	0x57, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x37, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x64, 0x0a, 0x21, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74,
	0x72, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x41, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x73, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x61, 0x73, 0x49, 0x64, 0x12, 0x28, 0x0a,
	0x10, 0x6d, 0x61, 0x73, 0x5f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x61, 0x73, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0xcc, 0x01, 0x0a, 0x16, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64,
	0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x41,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0b, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xb8, 0x01, 0x0a, 0x16, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x41, 0x75, 0x74,
	0x68, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x5f, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x4f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x72, 0x22, 0x47, 0x0a, 0x1f, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74,
	0x72, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x55, 0x69, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x54, 0x4c, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x73, 0x0a, 0x1c, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63,
	0x55, 0x69, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x3f,
	0x0a, 0x03, 0x74, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x55, 0x69, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x54, 0x4c, 0x53, 0x52, 0x03, 0x74, 0x6c, 0x73, 0x22,
	0x34, 0x0a, 0x1e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61,
	0x6c, 0x53, 0x70, 0x65, 0x63, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x22,
	0x82, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x36, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x12, 0x32, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x06, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x73, 0x22, 0x5d, 0x0a, 0x19, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43,
	0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61,
	0x6c, 0x12, 0x40, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x22, 0xad, 0x01, 0x0a, 0x28, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43,
	0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x6f, 0x53, 0x63, 0x61, 0x6c,
	0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x73, 0x22, 0x65, 0x0a, 0x21, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65,
	0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x1b, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63,
	0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x44, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x22, 0xa3, 0x01,
	0x0a, 0x19, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c,
	0x53, 0x70, 0x65, 0x63, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x4b, 0x0a, 0x08, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e,
	0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x53,
	0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x52, 0x08,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x02, 0x64, 0x62, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72,
	0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x44, 0x62, 0x52,
	0x02, 0x64, 0x62, 0x22, 0xc7, 0x03, 0x0a, 0x12, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43,
	0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x12, 0x38, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70,
	0x65, 0x63, 0x41, 0x75, 0x74, 0x68, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x4b, 0x0a, 0x0b,
	0x75, 0x69, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2a, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53,
	0x70, 0x65, 0x63, 0x55, 0x69, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0a, 0x75,
	0x69, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x51, 0x0a, 0x0d, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2c, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70,
	0x65, 0x63, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0c,
	0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x08,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x43, 0x65,
	0x6e, 0x74, 0x72, 0x61, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x08, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x41, 0x0a, 0x07, 0x63, 0x65, 0x6e, 0x74, 0x72,
	0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43,
	0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61,
	0x6c, 0x52, 0x07, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x12, 0x41, 0x0a, 0x07, 0x73, 0x63,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x53, 0x63, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x52, 0x07, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0xd3, 0x01,
	0x0a, 0x0e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x12, 0x40, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e,
	0x74, 0x72, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65, 0x6e, 0x74, 0x72,
	0x61, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x25, 0x0a, 0x0e,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x39, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61,
	0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x4f,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x43, 0x65,
	0x6e, 0x74, 0x72, 0x61, 0x6c, 0x52, 0x08, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x73, 0x32,
	0xd9, 0x01, 0x0a, 0x13, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x6c, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28,
	0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x65,
	0x6e, 0x74, 0x72, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x65, 0x6e, 0x74,
	0x72, 0x61, 0x6c, 0x73, 0x12, 0x20, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x63, 0x5a, 0x61, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x72,
	0x6f, 0x78, 0x2f, 0x61, 0x63, 0x73, 0x2d, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2d, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x69,
	0x6e, 0x6f, 0x73, 0x61, 0x75, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2d, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescOnce sync.Once
	file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescData = file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDesc
)

func file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescGZIP() []byte {
	file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescOnce.Do(func() {
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescData)
	})
	return file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDescData
}

var file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_goTypes = []interface{}{
	(*CentralVersions)(nil),                          // 0: fleetmanager.CentralVersions
	(*Condition)(nil),                                // 1: fleetmanager.Condition
	(*CentralStatus)(nil),                            // 2: fleetmanager.CentralStatus
	(*UpdateCentralStatusRequest)(nil),               // 3: fleetmanager.UpdateCentralStatusRequest
	(*UpdateCentralStatusResponse)(nil),              // 4: fleetmanager.UpdateCentralStatusResponse
	(*ManagedCentralMetadataAnnotations)(nil),        // 5: fleetmanager.ManagedCentralMetadataAnnotations
	(*ManagedCentralMetadata)(nil),                   // 6: fleetmanager.ManagedCentralMetadata
	(*ManagedCentralSpecAuth)(nil),                   // 7: fleetmanager.ManagedCentralSpecAuth
	(*ManagedCentralSpecUiEndpointTLS)(nil),          // 8: fleetmanager.ManagedCentralSpecUiEndpointTLS
	(*ManagedCentralSpecUiEndpoint)(nil),             // 9: fleetmanager.ManagedCentralSpecUiEndpoint
	(*ManagedCentralSpecDataEndpoint)(nil),           // 10: fleetmanager.ManagedCentralSpecDataEndpoint
	(*ResourceList)(nil),                             // 11: fleetmanager.ResourceList
	(*ResourceRequirements)(nil),                     // 12: fleetmanager.ResourceRequirements
	(*ManagedCentralSpecCentral)(nil),                // 13: fleetmanager.ManagedCentralSpecCentral
	(*ManagedCentralSpecScannerAnalyzerScaling)(nil), // 14: fleetmanager.ManagedCentralSpecScannerAnalyzerScaling
	(*ManagedCentralSpecScannerAnalyzer)(nil),        // 15: fleetmanager.ManagedCentralSpecScannerAnalyzer
	(*ManagedCentralSpecScannerDb)(nil),              // 16: fleetmanager.ManagedCentralSpecScannerDb
	(*ManagedCentralSpecScanner)(nil),                // 17: fleetmanager.ManagedCentralSpecScanner
	(*ManagedCentralSpec)(nil),                       // 18: fleetmanager.ManagedCentralSpec
	(*ManagedCentral)(nil),                           // 19: fleetmanager.ManagedCentral
	(*GetCentralsRequest)(nil),                       // 20: fleetmanager.GetCentralsRequest
	(*GetCentralsResponse)(nil),                      // 21: fleetmanager.GetCentralsResponse
	nil,                                              // 22: fleetmanager.UpdateCentralStatusRequest.UpdatesEntry
}
var file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_depIdxs = []int32{
	1,  // 0: fleetmanager.CentralStatus.conditions:type_name -> fleetmanager.Condition
	0,  // 1: fleetmanager.CentralStatus.versions:type_name -> fleetmanager.CentralVersions
	22, // 2: fleetmanager.UpdateCentralStatusRequest.updates:type_name -> fleetmanager.UpdateCentralStatusRequest.UpdatesEntry
	5,  // 3: fleetmanager.ManagedCentralMetadata.annotations:type_name -> fleetmanager.ManagedCentralMetadataAnnotations
	8,  // 4: fleetmanager.ManagedCentralSpecUiEndpoint.tls:type_name -> fleetmanager.ManagedCentralSpecUiEndpointTLS
	11, // 5: fleetmanager.ResourceRequirements.requests:type_name -> fleetmanager.ResourceList
	11, // 6: fleetmanager.ResourceRequirements.limits:type_name -> fleetmanager.ResourceList
	12, // 7: fleetmanager.ManagedCentralSpecCentral.resources:type_name -> fleetmanager.ResourceRequirements
	12, // 8: fleetmanager.ManagedCentralSpecScannerAnalyzer.resources:type_name -> fleetmanager.ResourceRequirements
	15, // 9: fleetmanager.ManagedCentralSpecScanner.analyzer:type_name -> fleetmanager.ManagedCentralSpecScannerAnalyzer
	16, // 10: fleetmanager.ManagedCentralSpecScanner.db:type_name -> fleetmanager.ManagedCentralSpecScannerDb
	7,  // 11: fleetmanager.ManagedCentralSpec.auth:type_name -> fleetmanager.ManagedCentralSpecAuth
	9,  // 12: fleetmanager.ManagedCentralSpec.ui_endpoint:type_name -> fleetmanager.ManagedCentralSpecUiEndpoint
	10, // 13: fleetmanager.ManagedCentralSpec.data_endpoint:type_name -> fleetmanager.ManagedCentralSpecDataEndpoint
	0,  // 14: fleetmanager.ManagedCentralSpec.versions:type_name -> fleetmanager.CentralVersions
	13, // 15: fleetmanager.ManagedCentralSpec.central:type_name -> fleetmanager.ManagedCentralSpecCentral
	17, // 16: fleetmanager.ManagedCentralSpec.scanner:type_name -> fleetmanager.ManagedCentralSpecScanner
	6,  // 17: fleetmanager.ManagedCentral.metadata:type_name -> fleetmanager.ManagedCentralMetadata
	18, // 18: fleetmanager.ManagedCentral.spec:type_name -> fleetmanager.ManagedCentralSpec
	19, // 19: fleetmanager.GetCentralsResponse.centrals:type_name -> fleetmanager.ManagedCentral
	2,  // 20: fleetmanager.UpdateCentralStatusRequest.UpdatesEntry.value:type_name -> fleetmanager.CentralStatus
	3,  // 21: fleetmanager.FleetManagerPrivate.UpdateCentralStatus:input_type -> fleetmanager.UpdateCentralStatusRequest
	20, // 22: fleetmanager.FleetManagerPrivate.GetCentrals:input_type -> fleetmanager.GetCentralsRequest
	4,  // 23: fleetmanager.FleetManagerPrivate.UpdateCentralStatus:output_type -> fleetmanager.UpdateCentralStatusResponse
	21, // 24: fleetmanager.FleetManagerPrivate.GetCentrals:output_type -> fleetmanager.GetCentralsResponse
	23, // [23:25] is the sub-list for method output_type
	21, // [21:23] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_init() }
func file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_init() {
	if File_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CentralVersions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Condition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CentralStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCentralStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCentralStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentralMetadataAnnotations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentralMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentralSpecAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentralSpecUiEndpointTLS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentralSpecUiEndpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentralSpecDataEndpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceRequirements); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentralSpecCentral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentralSpecScannerAnalyzerScaling); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentralSpecScannerAnalyzer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentralSpecScannerDb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentralSpecScanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentralSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedCentral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCentralsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCentralsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_goTypes,
		DependencyIndexes: file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_depIdxs,
		MessageInfos:      file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_msgTypes,
	}.Build()
	File_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto = out.File
	file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_rawDesc = nil
	file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_goTypes = nil
	file_internal_dinosaur_pkg_api_private_grpc_fleet_manger_private_proto_depIdxs = nil
}
